# Generated by Django 4.1.7 on 2023-09-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('practice_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farm.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_images',
            field=models.ManyToManyField(related_name='farms', to='farm.farmimage'),
        ),
        migrations.AddField(
            model_name='farm',
            name='products',
            field=models.ManyToManyField(related_name='farms', to='product.product'),
        ),
    ]
